### ISSUE TITLE
image link broken for youtube

### ISSUE THREAD

**Issue by nairvarun** [Kendall-Does-Coding-Websites/.github#2]
error message on https://svgshare.com/i/d5w.svg - This application is temporarily over its serving quota. Please try again later.

**Comment by TechStudent10** [comment]
Hm? It's working fine for me

![image](https://user-images.githubusercontent.com/76978184/154150743-8e4cf6b9-3373-49a5-be03-13af29ec585e.png)

**Comment by nairvarun** [comment]
ah. must've been some issue on my end

**Comment by KendallDoesCoding** [comment]
> ah. must've been some issue on my end

Yeah, the svgshare website goes down. I am planning to add the .svg file straight into the repo so it won't go down.
